@startuml
actor User

User -> TareaVista: Abrir el programa.
activate TareaVista
TareaVista -> TareaVista: mostrarMenu()


User -> TareaVista: Agregar tarea
TareaVista -> TareaVista: agregarTarea()
TareaVista -> TareaServicio: agregarTarea(Tarea tarea)
activate TareaServicio
TareaServicio -> TareaRepositorio: agregarTarea(Tarea tarea)
activate TareaRepositorio
TareaVista -> TareaVista: listarTareas()
TareaVista -> TareaServicio: obtenerTareas()
TareaServicio -> TareaRepositorio: seleccionarTodasLasTareas()
TareaRepositorio -> TareaServicio: List<Tarea>
deactivate TareaRepositorio
TareaServicio --> TareaVista: List<Tarea>
deactivate TareaServicio
TareaVista --> User: Se muestran las tareas en la tabla

User -> TareaVista: Modificar Tarea
TareaVista -> TareaVista: modificarTarea()
TareaVista -> TareaServicio: modificarTarea(Tarea tareaModificada)
activate TareaServicio
TareaServicio -> TareaRepositorio: modificarTarea(Tarea tareaModificada)
activate TareaRepositorio
TareaVista --> User: Éxito: Tarea modificada exitosamente
TareaVista -> TareaVista: mostrarTareas()
TareaVista -> TareaServicio: obtenerTareas()
TareaServicio -> TareaRepositorio: seleccionarTodasLasTareas()
TareaRepositorio -> TareaServicio: List<Tarea>
deactivate TareaRepositorio
TareaServicio --> TareaVista: List<Tarea>
deactivate TareaServicio
TareaVista --> User: Se muestran las tareas en la tabla

User -> TareaVista: Eliminar Tarea
TareaVista -> TareaVista: eliminarTarea()
TareaVista -> TareaServicio: eliminarTarea(int tareaId)
activate TareaServicio
TareaServicio -> TareaRepositorio: eliminarTareaPorId(int tareaId)
activate TareaRepositorio
TareaVista -> TareaVista: mostrarTareas()
TareaVista -> TareaServicio: obtenerTareas()
TareaServicio -> TareaRepositorio: seleccionarTodasLasTareas()
TareaRepositorio -> TareaServicio: List<Tarea>
deactivate TareaRepositorio
TareaServicio --> TareaVista: List<Tarea>
deactivate TareaServicio
TareaVista --> User: Se muestran las tareas en la tabla
deactivate TareaVista

@enduml